name: Test ACT

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test step
      run: |
        echo "Hello from ACT!"
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        
    - name: Test Docker
      run: |
        echo "Testing Docker..."
        docker --version
        docker info --format '{{.ServerVersion}}'
        
    - name: Test Python
      run: |
        echo "Testing Python..."
        python3 --version
        python3 -c "print('Python is working!')"
